title: Wicky # your site title
author: wicky-info
email: wickyandreanpallo@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Article about programing.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wicky-info.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WickyAndrean # replace with your_twitter_username or comment to remove link from footer
github_username:  wicky-info # replace with your_github_username or comment to remove link from footer
instagram_username: wicky.andrian.pallo # replace with your_instagram_username or comment to remove link from footer
social:
  name: Wicky
  links:
    - https://twitter.com/WickyAndrean
    - https://github.com/wicky-info+
    

disqus:
  shortname: blog33 # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
